# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_workings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
