# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_workings', '0002_auto_20171028_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(default='no', max_length=30),
            preserve_default=False,
        ),
    ]
