# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_workings', '0003_auto_20171028_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='bathroom',
            field=models.CharField(default='none', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
